[project]
name = "backend"
version = "0.1.0"
description = "Backend API for Cryage crypto agent"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "python-multipart>=0.0.6",
]